version: '1.1.{build}.0'
image: Visual Studio 2017

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore SevenZip.sln

environment:
  COVERALLS_REPO_TOKEN:  
    secure: uhHSJvf0G4qxIzWt2740yqjI1a5jGRM0bUFdf3nWGUYrHBc0rJXHn0wExDiWMz/O

build:
  parallel: true
  project: 'SevenZip.sln'
  publish_nuget: true

after_build:
  - cmd: nuget pack package.nuspec -version "%APPVEYOR_BUILD_VERSION%"

after_test: 
  - cmd: dotnet test SevenZip.Tests\SevenZip.Tests.csproj /p:CollectCoverage=true --no-build --configuration Release /p:CoverletOutput="%APPVEYOR_BUILD_FOLDER%\coverage.xml" /p:CoverletOutputFormat=opencover
  - ps: Invoke-Expression ($env:USERPROFILE + '\.nuget\packages\coveralls.io.\1.4.2\tools\coveralls.net.exe --opencover "%APPVEYOR_BUILD_FOLDER%\coverage.xml" -r %COVERALLS_REPO_TOKEN%')

artifacts:
  - path: 'Squid-Box.SevenZip*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: AWbl6aAa09NxVWFo9EDRC12RhY090havc8aWB9j0S4crFvICIkIvON0gUxG2q8QZ
  artifact: /SevenZip.*\.nupkg/
  skip_symbols: false
  on:
    branch: master
